# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coments',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
